name: update resource-parser form KOP-XIAO

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:      # 允许手动点一下执行

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取自己的仓库
        uses: actions/checkout@v4

      - name: 下载别人仓库的指定文件
        run: |
          # ====================== 只需要改这 4 项 ======================
          OWNER="KOP-XIAO"          # 别人的GitHub用户名
          REPO="QuantumultX"           # 别人的仓库名
          BRANCH="master"           # 对方分支（一般main/master）
          FILE_PATH="Scripts/resource-parser.js" # 对方文件路径（仓库里的完整路径）
          # ==============================================================

          # 下载地址
          URL="https://raw.githubusercontent.com/$OWNER/$REPO/$BRANCH/$FILE_PATH"

          # 下载到你仓库的 same path（会覆盖）
          curl -o "Script/resource-parser.js" "$URL"

      - name: 提交并推送更新
        uses: EndBug/add-and-commit@v9
        with:
          message: "自动同步文件: ${{ env.FILE_PATH }}"
          committer_name: GitHub Actions
          committer_email: actions@github.com
